theme: jekyll-theme-dinky

# Added information below.
title: "Sophie Engle"
description: "Simple profile website for Spring 2020."

# Enables using emoji. See: https://help.github.com/en/articles/emoji-on-github-pages
plugins:
  - jemoji
